# dbt Project Configuration
# =========================
# Crypto Trading Analytics Data Warehouse
#
# Usage:
#   dbt run            # Run all models
#   dbt test           # Run all tests
#   dbt docs generate  # Generate documentation
#   dbt docs serve     # Serve documentation locally

name: 'crypto_analytics'
version: '1.0.0'
config-version: 2

# Project paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

# Clean targets
clean-targets:
  - "target"
  - "dbt_packages"

# Profile (database connection)
profile: 'crypto_analytics'

# Model configurations
models:
  crypto_analytics:
    # Staging models: raw data cleansing
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging', 'raw']

    # Intermediate models: business logic transformations
    intermediate:
      +materialized: table
      +schema: intermediate
      +tags: ['intermediate', 'transform']

    # Marts models: final analytical tables
    marts:
      +materialized: table
      +schema: marts
      +tags: ['marts', 'analytics']

# Variables
vars:
  # Date range for processing
  start_date: '2020-01-01'
  end_date: '{{ run_started_at }}'

  # Default symbols
  symbols: ['BTC', 'ETH', 'XRP', 'TRX', 'ADA', 'DOGE']

  # Feature calculation parameters
  ma_short: 5
  ma_long: 20
  volatility_window: 20
  rsi_period: 14

# Tests
tests:
  +severity: warn
