# dbt Profile Configuration
# =========================
# Database connection profiles for different environments.
#
# Default: DuckDB for local development
# For production: Configure BigQuery or other warehouse

crypto_analytics:
  target: dev

  outputs:
    # Development: DuckDB (local file-based)
    dev:
      type: duckdb
      path: '../data/warehouse/crypto_analytics.duckdb'
      threads: 4

    # Production: DuckDB (can be swapped for BigQuery/Snowflake)
    prod:
      type: duckdb
      path: '../data/warehouse/crypto_analytics_prod.duckdb'
      threads: 8

    # BigQuery (example configuration)
    # bigquery:
    #   type: bigquery
    #   method: service-account
    #   project: your-gcp-project
    #   dataset: crypto_analytics
    #   threads: 4
    #   keyfile: /path/to/keyfile.json
    #   location: US
